cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/custom/InputFormEditText.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/custom/MaskWatcher.kt
Se corrige error al copiar el numero de tarjeta.
=> [Fix] copy paste card number

CHANGELOG.md, buildSrc/src/main/java/Versions.kt
Se actualiza Card Form a la versión 1.0.3
=> [Release] Update CardForm to 1.0.3

cardform/src/main/java/com/mercadolibre/android/cardform/di/module/ViewModelModule.kt, cardform/src/main/java/com/mercadolibre/android/cardform/tracks/CardFormTracker.kt
Se arreglan tracks, no se estaba mandando `session_time`
=> [FIX] fixed track session_time

cardform/src/main/java/com/mercadolibre/android/cardform/CardForm.kt
Se agrega reset cuando se inicia desde un Activity.
=> [FIX] Reset for activity start added

CHANGELOG.md, buildSrc/src/main/java/Versions.kt
=> [ci deploy]

cardform/src/main/java/com/mercadolibre/android/cardform/data/service/CardService.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/CardFormFragment.kt
=> [enhancement] odr flag added

cardform/src/main/java/com/mercadolibre/android/cardform/data/model/response/CardUi.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/model/response/Validation.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/helpers/ValidationHelper.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/DigitValidation.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/ValidationType.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/custom/InputFormEditText.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/CardNameFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/CardNumberFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/IdentificationFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/SecurityFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/viewmodel/InputFormViewModel.kt, cardform/src/main/res/layout/cf_input_form_edittext.xml
Se agrega validación en el séptimo dígito para tarjetas digitales.
=> [Feature] Seventh digit validation added

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/DigitValidation.kt
Se cambio la validación del 7mo dígito.
=> [FIX] Change validation

cardform/src/main/java/com/mercadolibre/android/cardform/data/model/response/Validation.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/DigitValidation.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/ValidationType.kt
Se cambia el valor a evaluar en la validación por una lista de valores posibles.
[video](https://drive.google.com/open?id=1qZJ5wyvI9KKINrHg97vIRENyA9Frrfuy)
=> [FIX] Change validation for seventh digit

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/extensions/FragmentExtensions.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/mapper/CardDataMapper.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/CardData.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/CardFormFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/FragmentNavigationController.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/custom/InputFormEditText.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/CardNumberFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/IdentificationFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/IssuersFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/SecurityFragment.kt, cardform/src/main/res/layout-h480dp/cf_card.xml, cardform/src/main/res/layout-h640dp/cf_card.xml, cardform/src/main/res/layout-h720dp/cf_card.xml, cardform/src/main/res/layout/app_bar.xml, cardform/src/main/res/layout/cf_card.xml, cardform/src/main/res/layout/cf_input_form_edittext.xml, cardform/src/main/res/layout/fragment_card_form.xml, cardform/src/main/res/layout/fragment_identification.xml, cardform/src/main/res/values-en/strings.xml, cardform/src/main/res/values-es-rAR/strings.xml, cardform/src/main/res/values-es-rCL/strings.xml, cardform/src/main/res/values-es-rCO/strings.xml, cardform/src/main/res/values-es-rMX/strings.xml, cardform/src/main/res/values-es-rPE/strings.xml, cardform/src/main/res/values-es-rVE/strings.xml, cardform/src/main/res/values-pt-rBR/strings.xml, cardform/src/main/res/values/strings.xml
Se agrega accesibilidad al alta de tarjeta
=> [Feature] Accessibility

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/custom/ProgressFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/CardNameFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/IdentificationFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/SecurityFragment.kt
Se fixean los siguientes errores:
https://mercadolibre.atlassian.net/browse/MPMOB-551
https://mercadolibre.atlassian.net/browse/MPMOB-335
https://mercadolibre.atlassian.net/browse/MPMOB-365
=> [Fix] Input card name and security fixed

CHANGELOG.md, buildSrc/src/main/java/Versions.kt
Update cardform version to `1.3.1`
=> [Release] Update cardform version

CHANGELOG.md, app/src/main/java/com/mercadolibre/android/example/OneTapFragment.kt, app/src/main/java/com/mercadolibre/android/example/SampleActivity.kt, buildSrc/src/main/java/Versions.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/service/TokenizeService.kt
- Se corrige error en el request de card token
=> [Fix] Card token request

cardform/src/main/java/com/mercadolibre/android/cardform/CardForm.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/CardFormFragment.kt
Signed-off-by: Gabriel Cerceau <gabriel.cerceau@mercadolibre.com>
=> Return the card id when a new card is registered

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/CardFormFragment.kt, cardform/src/main/res/layout-h480dp/cf_card.xml, cardform/src/main/res/layout/activity_card_form.xml, cardform/src/main/res/layout/app_bar.xml, cardform/src/main/res/values/colors.xml, cardform/src/main/res/values/styles.xml
=> [Feature] Updated meli colors

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/res/values/styles.xml, buildSrc/src/main/java/Versions.kt, cardform/src/main/AndroidManifest.xml, cardform/src/main/res/layout/app_bar.xml, cardform/src/main/res/values-v21/styles.xml, cardform/src/main/res/values/colors.xml, cardform/src/main/res/values/styles.xml
- Fix activity status bar color.
=> [Release] 1.5.1

CHANGELOG.md, buildSrc/src/main/java/Versions.kt, cardform/src/main/res/values-v21/styles.xml, cardform/src/main/res/values/colors.xml
* Adjusted status bar color again
=> [Release] 1.5.2

CHANGELOG.md, buildSrc/src/main/java/Versions.kt
- Null pointer on view model in IssuerFragment
=> [Release] Update card form to 1.7.0

cardform/src/main/java/com/mercadolibre/android/cardform/network/interceptor/SessionInterceptor.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/CardFormWebViewFragment.kt
* Se empieza a usar la configuración default en la cache de la webview.
* Se concatena header `"NoIframe"`.
* Se arregla header de session id.
=> [Fix] Cache webview fixed, header session id fixed

CHANGELOG.md, buildSrc/src/main/java/Versions.kt
- Card token model modified to support esc null, tokenize use case mapping fixed
=> [Release] Changelog and app version updated

CHANGELOG.md, buildSrc/src/main/java/Versions.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/ErrorUtil.kt
Change MeliSnackbar for AndesSnackbar
| Al colocar mal el PAN | Al no tener Internet y querer agregar la tarjeta
| ------------- | ------------- |
| ![Screenshot_1614794597](https://user-images.githubusercontent.com/53618779/109850902-ca0ca480-7c31-11eb-87b4-0bb81b5f3414.png) | ![Screenshot_1614795195](https://user-images.githubusercontent.com/53618779/109852059-20c6ae00-7c33-11eb-9484-d1f6a0242888.png) |
=> Andes Snackbar

CHANGELOG.md
- Change MeliSnackbar for AndesSnackbar
- Soft keyboard behaviour fixed
=> [Release] Update Cardform to 1.7.0

cardform/src/main/java/com/mercadolibre/android/cardform/CardForm.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/repository/CardRepositoryImpl.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/service/CardService.kt, cardform/src/main/java/com/mercadolibre/android/cardform/di/Dependencies.kt, cardform/src/main/java/com/mercadolibre/android/cardform/di/module/RepositoryModule.kt, cardform/src/main/java/com/mercadolibre/android/cardform/internal/CardFormWithFragment.kt
Agregamos un nuevo endpoint para el get card info, para usarlo desde el market place que filtra los bines dependiendo los items
=> add new endpoint get card info from marketplace

cardform/src/main/java/com/mercadolibre/android/cardform/CardForm.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/StateUi.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/CardFormFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/viewmodel/InputFormViewModel.kt
Se agrega en el result el bin y el payment_type_id de la tarjeta enrolada.
=> [CHO-6508] Result with bin and payment_type

cardform/src/main/java/com/mercadolibre/android/cardform/CardForm.kt, cardform/src/main/java/com/mercadolibre/android/cardform/domain/TokenizeUseCase.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/CardFormFragment.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/viewmodel/InputFormViewModel.kt
Se agrega en el result los últimos cuatro digitos de la tarjeta enrolada.
=> [CHO-6508] Result with lastFourDigits

cardform/src/main/res/layout/app_bar.xml, cardform/src/main/res/values/styles.xml
Se agrega un estilo de texto en el toolbar personalizable
=> [CHO-6639] customizable toolbar text style

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/custom/InputFormEditText.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/CardNameFragment.kt
https://mercadolibre.atlassian.net/browse/PXN-2332
https://mercadolibre.atlassian.net/browse/PXN-2345
=> [fix] trim white spaces from input text

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/custom/InputFormEditText.kt, cardform/src/main/java/com/mercadolibre/android/cardform/presentation/ui/formentry/CardNameFragment.kt
https://mercadolibre.atlassian.net/browse/PXN-2333
=> [fix] improved watcher validation to avoid ANR

cardform/src/main/java/com/mercadolibre/android/cardform/data/repository/CardAssociationRepositoryImpl.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/repository/FinishInscriptionRepositoryImpl.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/repository/InscriptionRepositoryImpl.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/repository/TokenizeRepositoryImpl.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/service/CardAssociationService.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/service/FinishInscriptionService.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/service/InscriptionService.kt, cardform/src/main/java/com/mercadolibre/android/cardform/data/service/TokenizeService.kt, cardform/src/main/java/com/mercadolibre/android/cardform/di/Dependencies.kt, cardform/src/main/java/com/mercadolibre/android/cardform/di/module/NetworkModule.kt, cardform/src/main/java/com/mercadolibre/android/cardform/di/module/RepositoryModule.kt, cardform/src/main/java/com/mercadolibre/android/cardform/network/HttpClientFactory.kt, cardform/src/main/java/com/mercadolibre/android/cardform/network/RetrofitFactory.kt, cardform/src/main/java/com/mercadolibre/android/cardform/network/interceptor/AuthorizationInterceptor.kt
The access token is now passed in the header calls.
=> change the access token parameter to header

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/mapper/CardInfoMapper.kt
Reverts mercadolibre/card-form-android#123
=> Revert "removed punctuation on identification number"

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/mapper/CardInfoMapper.kt
GET https://api.mercadopago.com/production/px_mobile/v1/card?bin=424242&site_id=MLB&odr=true
accept-language: en
user-agent: CardForm/Android/2.1.1
x-density: xhdpi
X-Session-Id: 7e9adc88-9b90-4241-8a3a-fa6dfea0f955
X-Flow-Id: test_flow
Authorization: Bearer APP_USR-4859545258837789-070521-842601854aebe5cece5b146885b53c7f-771993156
--> END GET
D/OkHttp: <-- 200 https://api.mercadopago.com/production/px_mobile/v1/card?bin=424242&site_id=MLB&odr=true (742ms)
date: Thu, 18 Nov 2021 13:25:46 GMT
content-type: application/json;charset=utf-8
vary: Accept-Encoding
vary: Accept,Accept-Encoding
cache-control: max-age=0
x-content-type-options: nosniff
x-request-id: bc195a4f-b7bc-40a7-ae57-8d8f073a4b7a
x-xss-protection: 1; mode=block
strict-transport-security: max-age=16070400; includeSubDomains; …
=> removed punctuation on identification number

CHANGELOG.md, buildSrc/src/main/java/Versions.kt
Reverts mercadolibre/card-form-android#126
=> Revert "[Release] Update version to 2.1.2""

CHANGELOG.md, README.md, buildSrc/src/main/java/Versions.kt
- Fix - Remove junit 5 gradle plugins.
=> [Release] 2.2.2

cardform/src/main/java/com/mercadolibre/android/cardform/presentation/model/BinValidator.kt
We are going to start to send 8 digits for bin validation in api call to get the card configuration
=> [feautre] add support for bin 8
